# generated by Git for Windows
test -f ~/.profile && . ~/.profile
test -f ~/.bashrc && . ~/.bashrc

test -f ~/.bashrc && . ~/.bashrc
test -f ~/.bashrc && . ~/.bashrc
alias sx="source ~/.bash_profile"
source ~/.alias
source ~/.perforcealias
